import React, {useEffect, useState} from 'react';
import Head from 'next/head'
import axios from "axios";
import {Container, Row, Col, Button, Spinner} from "reactstrap";
import Loader from "../components/Loader";
// import {Button} from "bootstrap";


export default function Home() {
  const [categories, setCategories] = useState([])
  const [loadingCategories, setLoadingCategories] =  useState(false);
  const [url, setUrl] = useState('');
  const [checkoutURLLoading, setCheckoutURLLoading] = useState(false);

  const getCategories = async () => {
    setLoadingCategories(true);
    try {
      const {data} = await axios.get('http://localhost:3000/api/categories');
      console.log(data)
      setCategories(data.categories);
      setLoadingCategories(false)
    } catch (e) {
      throw e;
    }
    setLoadingCategories(false)
  }

  const onChosenCategory = async (category) => {
    setCheckoutURLLoading(true);
    try {
      const {data} = await axios.get('http://localhost:3000/api/randomBook', {
        params: {url: category}
      });
      setUrl(data.url);
      setCheckoutURLLoading(false)
    } catch (e) {
      throw e;
    }
    setCheckoutURLLoading(false);
  }

  useEffect(() => {
    getCategories()
  }, [])

  return (
    <>
      <Head>
        <title>Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="vh-100">
        <Container  className="d-flex flex-column h-100" >
          <>
            {
              url !== '' || checkoutURLLoading ? (
                  <>
                    {
                      checkoutURLLoading ? (
                          <div className="m-auto">
                            <Loader text="Generating link for book" />
                          </div>
                      ) : (
                          <>
                            <h1 className="my-5 text-center">You can buy your book by clicking button bellow</h1>
                            <a href={url} target="_blank" rel="noreferrer" className="d-inline-block mx-auto px-3">
                              <Button color="primary" >
                                Buy
                              </Button>
                            </a>
                          </>
                      )
                    }
                  </>
              ) : (
                  <>
                    {
                      loadingCategories ? (
                          <div className="m-auto">
                            <Loader text="Loading categories" />
                          </div>
                      ) : (
                          <>
                            <h1 className="my-5 text-center">Pick the book category that you like</h1>
                            <div className="w-50 mx-auto">
                              {
                                categories.length > 0 && categories.map((category) => (
                                    <a href="#0" onClick={() => onChosenCategory(category.url)} className="d-block mb-2 text-center">
                                      {category.name}
                                    </a>
                                ))
                              }
                            </div>
                          </>
                      )
                    }
                  </>
              )
            }
          </>
        </Container>
      </main>
    </>
  )
}
